## Author
---
- **Name:** Nikhil Sivakumar, Izaak Van Til, Sam Stefanov
- **Email:** nsiva3@illinois.edu, ivantil2@illinois.edu, sstef3@illinois.edu
---

## Purpose

- An MLB article was published which ranked the best rotations in the MLB going into 2024. The Mariners were ranked number 1 over teams like the Braves and Dodgers. The five starting pitchers in the rotation all played at some point last year so the question is, "How good were the Mariners pitching rotation in 2023?" Their pitching rotation consists of Luis Castillo, George Kirby, Logan Gilbert, Bryan Woo and Bryce Miller.

## Data
- This application has data from the baseballr package. Baseballr is a package written for R
focused on baseball analytics and has data collected from other baseball databases such as FanGraphs,
Baseball-Reference, and baseballsavant.

## Reference
- [Analysis Video (For final presentation)](https://youtu.be/5p7b6EaHabE)
- [Best MLB rotations 2024](https://www.mlb.com/news/best-mlb-rotations-2024)
- [Baseballr packages github](https://github.com/billpetti/baseballr/tree/development_branch)
- [Luis Castillo Stats](https://baseballsavant.mlb.com/savant-player/luis-castillo-622491)
- [George Kirby Stats](https://baseballsavant.mlb.com/savant-player/george-kirby-669923)
- [Logan Gilbert Stats](https://baseballsavant.mlb.com/savant-player/logan-gilbert-669302)
- [Bryan Woo Stats](https://baseballsavant.mlb.com/savant-player/bryan-woo-693433)
- [Bryce Miller Stats](https://baseballsavant.mlb.com/savant-player/bryce-miller-682243)